[package]
name = "brickcheck"
version = "0.1.0"
authors = ["Jihyeok Seo <me@limeburst.net>"]
description = "brickcheck checks your firmware for brickers!"
repository = "https://github.com/limeburst/brickcheck"
readme = "README.md"
license = "MIT"

[dependencies]
bit-vec = "0.4.3"
